<?php

$title = 'Qualifications';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('qualification', ['action' => 'add']) ?>">Add new qualification</a>
</p>

<table class="table">
<tr>
    <th>Qualification description</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($qualifications as $qualification) : ?>
    <tr>
        <td><?= $this->escapeHtml($qualification->qualificationDescription) ?></td>
        <td>
            <a href="<?= $this->url('qualification', ['action' => 'edit', 'id' => $qualification->id]) ?>">Edit</a>
            <a href="<?= $this->url('qualification', ['action' => 'delete', 'id' => $qualification->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>