<?php
$title = 'Add new department';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$departmentName = $form->get('departmentName');
$departmentName->setAttribute('class', 'form-control');
$departmentName->setAttribute('placeholder', 'Department Name');

// This provides a default CSS class and placeholder text for the artist element:
$departmentDescription = $form->get('departmentDescription');
$departmentDescription->setAttribute('class', 'form-control');
$departmentDescription->setAttribute('placeholder', 'Department description');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('department', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($departmentName) ?>
    <?= $this->formElement($departmentName) ?>
    <?= $this->formElementErrors()->render($departmentName, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($departmentDescription) ?>
    <?= $this->formElement($departmentDescription) ?>
    <?= $this->formElementErrors()->render($departmentDescription, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();