<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Edit employee';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$lastName = $form->get('lastName');
$lastName->setAttribute('class', 'form-control');
$lastName->setAttribute('placeholder', 'Last name');

$firstName = $form->get('firstName');
$firstName->setAttribute('class', 'form-control');
$firstName->setAttribute('placeholder', 'First name');

$departmentId = $form->get('departmentId');
$departmentId->setAttribute('class', 'form-control');
$departmentId->setAttribute('placeholder', 'Department Id');

$qualification = $form->get('qualification');
$qualification->setAttribute('class', 'form-control');
$qualification->setAttribute('placeholder', 'Qualification');


$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('employee', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($lastName) ?>
    <?= $this->formElement($lastName) ?>
    <?= $this->formElementErrors()->render($lastName, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($firstName) ?>
    <?= $this->formElement($firstName) ?>
    <?= $this->formElementErrors()->render($firstName, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($departmentId) ?>
    <?= $this->formElement($departmentId) ?>
    <?= $this->formElementErrors()->render($departmentId, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($qualification) ?>
    <?= $this->formElement($qualification) ?>
    <?= $this->formElementErrors()->render($qualification, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();