<?php
// module/Album/view/album/album/index.phtml:

$title = 'Department';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('department', ['action' => 'add']) ?>">Add new department</a>
</p>

<table class="table">
<tr>
    <th>Department Name</th>
    <th>Department Description</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($departments as $department) : ?>
    <tr>
        <td><?= $this->escapeHtml($department->departmentName) ?></td>
        <td><?= $this->escapeHtml($department->departmentDescription) ?></td>
        <td>
            <a href="<?= $this->url('department', ['action' => 'edit', 'id' => $department->id]) ?>">Edit</a>
            <a href="<?= $this->url('department', ['action' => 'delete', 'id' => $department->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>