<?php
$title = 'Add new qualification';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
// This provides a default CSS class and placeholder text for the title element:
$qualificationType = $form->get('qualificationType');
$qualificationType->setAttribute('class', 'form-control');
$qualificationType->setAttribute('placeholder', 'Qualification Type');

$qualificationDescription = $form->get('qualificationDescription');
$qualificationDescription->setAttribute('class', 'form-control');
$qualificationDescription->setAttribute('placeholder', 'Qualification Description');
  
// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('qualification', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>
<?php // Wrap the elements in divs marked as form groups, and render the
      // label, element, and errors separately within ?>
<div class="form-group">
    <?= $this->formLabel($qualificationType) ?>
    <?= $this->formElement($qualificationType) ?>
    <?= $this->formElementErrors()->render($qualificationType, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($qualificationDescription) ?>
    <?= $this->formElement($qualificationDescription) ?>
    <?= $this->formElementErrors()->render($qualificationDescription, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();