<?php
$title = 'Delete qualification';
$url   = $this->url('qualification', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete
    <?= $this->escapeHtml($qualification->qualificationType) ?> with the description
    <?= $this->escapeHtml($qualification->qualificationDescription) ?>?
    
    
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $qualification->id ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Yes" />
    <input type="submit" class="btn btn-success" name="del" value="No" />
</div>
</form>