<?php

$title = 'Employees';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('employee', ['action' => 'add']) ?>">Add new employee</a>
</p>

<table class="table">
<tr>
    <th>Last Name</th>
    <th>First Name</th>
    <th>Department Id</th>
    <th>Qualification</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($employees as $employee) : ?>
    <tr>
        <td><?= $this->escapeHtml($employee->lastName) ?></td>
        <td><?= $this->escapeHtml($employee->firstName) ?></td>
        <td><?= $this->escapeHtml($employee->departmentId) ?></td>
        <td><?= $this->escapeHtml($employee->qualification) ?></td>
        <td>
            <a href="<?= $this->url('employee', ['action' => 'edit', 'id' => $employee->id]) ?>">Edit</a>
            <a href="<?= $this->url('employee', ['action' => 'delete', 'id' => $employee->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>